import { useState, useEffect } from 'react'

import './Popup.css'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  // useEffect(() => {
  //   // chrome.storage.sync.get(['count'], (result) => {
  //   //   setCount(result.count || 0)
  //   // })
  // }, [])

  useEffect(() => {
    // chrome.storage.sync.set({ count })
    chrome.runtime.sendMessage({ type: 'COUNT', count })
  }, [count])

  return (
    <main>
      <h1><a href="options.html" target="_blank">Options Page(extension settings/options)</a></h1>
      <h1><a href="home.html" target="_blank">Home Page(react-router demo)</a></h1>
      <h1><a href="popup.html" target="_blank">Popup Page(counter)</a></h1>
      <hr />
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus} disabled={count <= 0}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Popup
